### ISSUE TITLE
y axis label showing NaN and no line with character y

### ISSUE THREAD

**Issue by zji90** [juba/scatterD3#51] opened 2016-11-28 13:56 UTC
If character values are supplied for y, the labels for y axis becomes NaN. Also the lines do not appear (or it is not clear how to specify lines in this case). Numeric values are still supplied for x axis.

**Comment by juba** [comment] 2016-11-28 16:33
Could you please provide a reproducible example ?

**Comment by zji90** [comment] 2016-11-28 19:26
Hi Juba,
I incorporated the scatterD3 function in shiny. Please see below for an example:
scatterD3(c(267,239),c("a1","a2"),lab = c("b","c"), lines = data.frame(slope = 0, intercept = c(1,2)))

I am using the 0.8 version of scatterD3 package.

**Comment by juba** [comment] 2016-11-28 21:41
You're right for the `NaN` labels, it is even present in the package vignette, I'll take a look at it.

The lines seem to be working, though, but with a categorical y-axis, only vertical lines, with slope `Inf`, make sense. Something like this : 

    scatterD3(c(267,239),c("a1","a2"),
        lab = c("b","c"),
        lines = data.frame(slope = Inf, intercept = c(245, 248)))

**Comment by juba** [comment] 2016-11-29 08:22
Should be fixed now in the Github version. Thanks for taking the time to report the problem.

**Closed as completed** 2016-11-29 08:21 UTC

**Comment by zji90** [comment] 2016-11-29 11:08
Hi juba,
Thanks a lot for taking time to fix this. The y axis labels can now be shown. However, I do want to display straight lines for y (actually what I want to do here is to show some gene sequences and mark some specific sites on these sequence. Each y value represents a gene sequence and I want to use a straight line to represent this sequence). It will be even better if a line with a fixed lengths (going from (0,1) to (0,2) for example) can be drawn instead of an abline that has infinite length (since each gene has different lengths, this will be more useful for users to compare different genes). I am wondering whether this is possible to do in scatterD3? Thanks again!

**Comment by juba** [comment] 2016-11-30 19:56
Well, no, unfortunately there is no way to do this in the current `scatterD3` version, as the package is really intended for scatter plots, and so does not offer as many options as general purpose plotting libraries...

And I fear there would be no way to draw lines which for categorical axes, except lines perpendicular to those axes (if the second axis is numerical)...

**Comment by zji90** [comment] 2016-11-30 20:21
All right. Thanks for the response!
